name: MyFirstWorkflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    env:
        SECRET_WORD: ${{ secrets.SecretWord }}

    steps:
      - run: echo "👋 Hello World!"
      

      - name: Checkout
        uses: actions/checkout@v4.2.2

#      - name: Lint
#        uses: super-linter/super-linter@v7.1.0
      - name: Check Word
        run: |
            echo SECRET_WORD-
            echo "$SECRET_WORD"
    
      - name: List files
        run: |
          echo "The repository ${{ github.repository }} contains the following ➥files:"
          tree

      - name: CompletionCheck
        if: success()
        run: |
            echo "Completed as expected"
        
        

      
